### ISSUE TITLE
http://jmfriedt.org/sdcard.img has an image for zynq devices.

### ISSUE THREAD

**Issue by kazueda** [oscimp/PlutoSDR#1]
I found that sdcard.img on http://jmfriedt.org/sdcard.img is not an imge file for raspberry pi 4.  It's a image file for zynq devices.

**Comment by jmfriedt** [comment]
My apologies, I had mistakenly replaced the sdcard.img for the RPi4 with an image targeted to the Red Pitaya, emphasizing the flexibility of Buildroot supporting GNU Radio targeted to so many platforms. I have uploaded an image for the RPi4 back to this location, hopefully solving the issue. Apologies for the inconvenience.
